# Generated by Django 5.0.2 on 2024-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.TextField()),
                ('nome', models.TextField()),
                ('email', models.TextField()),
                ('telefone', models.TextField()),
                ('endereço', models.TextField()),
            ],
        ),
    ]
