# Generated by Django 5.0.2 on 2024-03-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
