# Generated by Django 5.0.2 on 2024-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0004_pet_id_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('cpf', models.TextField()),
                ('email', models.TextField()),
                ('telefone', models.TextField()),
                ('endereco', models.TextField()),
                ('salario', models.FloatField()),
                ('cargo', models.TextField()),
            ],
        ),
    ]
