# Generated by Django 5.0.2 on 2024-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0005_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('preco', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('validade', models.TextField()),
                ('categoria', models.TextField()),
            ],
        ),
    ]
