# Generated by Django 5.0.2 on 2024-03-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0008_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='servico_id',
            field=models.TextField(default=3),
        ),
    ]
