# Generated by Django 5.0.2 on 2024-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0009_servico_servico_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField()),
                ('vendedor_id', models.IntegerField()),
                ('formaDePagamento', models.TextField()),
                ('itens', models.JSONField()),
                ('datahora', models.DateTimeField()),
            ],
        ),
    ]
