# Generated by Django 5.0.3 on 2024-05-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0002_rename_endere�o_cliente_endereco'),
        ('appPetPlanet', '0011_venda_total'),
    ]

    operations = [
    ]
