# Generated by Django 5.0.2 on 2024-05-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0012_merge_20240528_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
