# Generated by Django 5.0.2 on 2024-03-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0006_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='validade',
            field=models.TextField(default='12/12/2099'),
        ),
    ]
