# Generated by Django 5.0.2 on 2024-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0007_alter_produto_validade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField()),
                ('cliente_id', models.IntegerField()),
                ('pet_id', models.IntegerField()),
                ('funcionario_id', models.IntegerField()),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
