# Generated by Django 5.0.2 on 2024-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0010_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.FloatField(default=1),
        ),
    ]
