# Generated by Django 5.0.2 on 2024-05-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPetPlanet', '0012_merge_20240526_1553'),
        ('appPetPlanet', '0013_rename_endereço_cliente_endereco'),
    ]

    operations = [
    ]
